const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DATA={1:{e:'🐰',name:'小兔',bg:'linear-gradient(145deg,#ff9a9e,#f7b7c5)'},2:{e:'🍎',name:'苹果',bg:'linear-gradient(145deg,#ff758c,#ff9b9b)'},3:{e:'⭐',name:'星星',bg:'linear-gradient(145deg,#ffc857,#ff9f5a)'},4:{e:'🐟',name:'小鱼',bg:'linear-gradient(145deg,#56ccf2,#4a9ff5)'},5:{e:'🌸',name:'小花',bg:'linear-gradient(145deg,#ff9dc7,#c58cff)'},6:{e:'🚗',name:'小车',bg:'linear-gradient(145deg,#57e5aa,#2ec7a6)'},7:{e:'🦋',name:'蝴蝶',bg:'linear-gradient(145deg,#9b8cff,#c89cff)'},8:{e:'🍭',name:'棒棒糖',bg:'linear-gradient(145deg,#55d8ff,#6c8cff)'},9:{e:'🎈',name:'气球',bg:'linear-gradient(145deg,#ff7ca8,#ffb55d)'}};
const CN=['','一','二','三','四','五','六','七','八','九'];
const MODES={recognize:{name:'翻牌认数字',hint:'翻开卡牌后，由大人判断答对或答错。'},find:{name:'找数字',hint:'根据提示，在九宫格里找到正确数字。'},count:{name:'数一数',hint:'数一数卡牌上的小物件，再选择正确数字。'}};
const state={mode:'recognize',count:5,race:false,time:30,selected:[],sequence:[],completed:new Set(),target:null,activeCard:null,activeNumber:null,score:0,streak:0,mistakes:0,attempts:0,locked:false,timerId:null,timerStart:0,raceTimeout:null,rewardTimer:null};
let audioWanted=true,audioCtx=null,masterGain=null;
const setupView=$('#setupView'),gameView=$('#gameView'),board=$('#board'),countArena=$('#countArena'),judgePanel=$('#judgePanel'),racePanel=$('#racePanel'),prompt=$('#prompt'),toast=$('#toast'),reward=$('#reward'),resultModal=$('#resultModal');
function shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
async function ensureAudio(){if(!audioWanted)return false;try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=.8;masterGain.connect(audioCtx.destination)}if(audioCtx.state!=='running')await audioCtx.resume();return audioCtx.state==='running'}catch(e){return false}}
function tone(f,d=.15,type='sine',vol=.45,delay=0){if(!audioWanted||!audioCtx||audioCtx.state!=='running')return;const start=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(vol,start+.025);g.gain.exponentialRampToValueAtTime(.001,start+d);o.connect(g);g.connect(masterGain);o.start(start);o.stop(start+d+.04)}
function sound(kind){if(kind==='flip'){tone(520,.1,'triangle',.35);tone(760,.12,'triangle',.32,.08)}if(kind==='ok'){tone(523,.16,'sine',.5);tone(659,.16,'sine',.5,.13);tone(784,.22,'sine',.48,.26)}if(kind==='bad'){tone(240,.16,'square',.18);tone(190,.22,'square',.16,.15)}if(kind==='finish'){[523,659,784,1046,1318].forEach((n,i)=>tone(n,.22,'sine',.5,i*.13))}}
function speak(text){if(!audioWanted||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/zh|Chinese|中文/i.test(v.lang+' '+v.name))||null;u.lang='zh-CN';u.rate=.88;u.pitch=1.12;u.volume=1;speechSynthesis.speak(u)}catch(e){}}
function showToast(text,ms=1300){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),ms)}
function modePrompt(){if(state.mode==='recognize')return '选一张卡牌，看看里面藏着哪个数字？';if(state.mode==='find')return `请找到数字 ${state.target}`;return '数一数：卡牌上有几个小物件？'}
function updateHUD(){const done=state.completed.size,total=state.selected.length;$('#modeName').textContent=MODES[state.mode].name;$('#scoreValue').textContent=state.score;$('#streakValue').textContent=state.streak?`🔥 ${state.streak}`:'—';$('#progressValue').textContent=`${done}/${total}`;$('#progressFill').style.width=`${total?done/total*100:0}%`}
function setPrompt(main,sub=''){prompt.innerHTML=`<div>${main}${sub?`<small>${sub}</small>`:''}</div>`}
function chooseMode(mode){state.mode=mode;$$('.mode-card').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function chooseCount(n){state.count=n;$$('.count-chip').forEach(b=>b.classList.toggle('active',Number(b.dataset.count)===n))}
function makeObjects(n,emoji,cls='obj'){return Array.from({length:n},()=>`<span class="${cls}">${emoji}</span>`).join('')}
function makeCard(n,frontVisible=false){const d=DATA[n],el=document.createElement('div');el.className=`number-card${frontVisible?' revealed find-card':''}`;el.dataset.number=n;el.innerHTML=`<div class="face back"><div class="q">?</div><div class="tap">点我翻开</div></div><div class="face front" style="background:${d.bg}"><div class="check-badge">✓</div><div class="digit">${n}</div><div class="objects">${makeObjects(n,d.e)}</div><div class="theme-label">${n} 个${d.name}</div></div>`;return el}
function fillBoard(cards){board.innerHTML='';for(let i=0;i<9;i++){const slot=document.createElement('div');slot.className='slot';if(i<cards.length)slot.appendChild(cards[i]);else slot.classList.add('empty');board.appendChild(slot)}}
function resetGameState(){stopRace(false,true);clearTimeout(state.rewardTimer);state.selected=shuffle([1,2,3,4,5,6,7,8,9]).slice(0,state.count);state.sequence=shuffle(state.selected);state.completed=new Set();state.target=null;state.activeCard=null;state.activeNumber=null;state.score=0;state.streak=0;state.mistakes=0;state.attempts=0;state.locked=false;judgePanel.classList.remove('show');reward.classList.remove('show');resultModal.classList.remove('show');countArena.classList.remove('show');board.classList.remove('hidden');updateHUD()}
async function startGame(){state.race=$('#raceToggle').checked;state.time=clamp(Number($('#timeInput').value)||30,5,120);state.count=Number($('.count-chip.active')?.dataset.count||state.count);if(audioWanted){await ensureAudio();sound('flip')}resetGameState();setupView.classList.add('hidden');gameView.classList.remove('hidden');$('#restartBtn').classList.remove('hidden');if(state.mode==='recognize')startRecognize();if(state.mode==='find')startFind();if(state.mode==='count')startCount()}
function startRecognize(){setPrompt('选一张卡牌，看看是什么数字',MODES.recognize.hint);fillBoard(state.selected.map(n=>{const c=makeCard(n);c.addEventListener('click',()=>revealRecognize(c,n));return c}))}
function revealRecognize(card,n){if(state.locked||state.activeCard||card.classList.contains('passed'))return;sound('flip');card.classList.add('revealed');state.activeCard=card;state.activeNumber=n;judgePanel.classList.add('show');setPrompt(`这是数字 ${n} 吗？`,'先让小朋友回答，再由大人判断');startRace(()=>recognizeWrong(true))}
function recognizeCorrect(){if(!state.activeCard||state.locked)return;const card=state.activeCard,n=state.activeNumber;stopRace(true);judgePanel.classList.remove('show');card.classList.add('passed','revealed');state.completed.add(n);state.attempts++;state.streak++;state.score+=10+Math.min((state.streak-1)*2,10);state.activeCard=null;state.activeNumber=null;sound('ok');speak(`恭喜你，答对了数字${CN[n]}`);updateHUD();showReward(n,'答对啦！',()=>{if(isFinished())finishGame();else setPrompt('继续选一张卡牌吧','答对的卡牌会留下绿色勾勾')})}
function recognizeWrong(timeout=false){if(!state.activeCard)return;const card=state.activeCard,n=state.activeNumber;stopRace(false,true);judgePanel.classList.remove('show');state.mistakes++;state.attempts++;state.streak=0;state.activeCard=null;state.activeNumber=null;state.locked=true;sound('bad');updateHUD();showToast(timeout?'时间到，再试一次！':'没关系，再试一次！');setTimeout(()=>card.classList.remove('revealed'),350);setTimeout(()=>shuffleCardWithHidden(card),700);setTimeout(()=>{state.locked=false;setPrompt('卡牌换位置啦，再选一张试试','答错的卡牌已经藏回去了')},1100)}
function shuffleCardWithHidden(card){const candidates=$$('.number-card').filter(c=>c!==card&&!c.classList.contains('passed')&&!c.classList.contains('revealed'));if(!candidates.length)return;const other=candidates[Math.floor(Math.random()*candidates.length)];card.classList.add('shuffle');other.classList.add('shuffle');setTimeout(()=>{swapNodes(card,other);card.classList.remove('shuffle');other.classList.remove('shuffle')},260)}
function swapNodes(a,b){const ap=a.parentNode,bp=b.parentNode,ph=document.createComment('swap');ap.replaceChild(ph,a);bp.replaceChild(a,b);ph.parentNode.replaceChild(b,ph)}
function startFind(){const cards=state.selected.map(n=>{const c=makeCard(n,true);c.addEventListener('click',()=>chooseFind(c,n));return c});fillBoard(cards);nextFind()}
function nextFind(){if(isFinished())return finishGame();state.target=state.sequence.find(n=>!state.completed.has(n));setPrompt(`请找到数字 ${state.target}`,'看清楚数字，再点一下正确卡牌');speak(`请找到数字${CN[state.target]}`);startRace(()=>findTimeout())}
function chooseFind(card,n){if(state.locked||card.classList.contains('passed'))return;if(n===state.target){stopRace(true);card.classList.add('passed');state.completed.add(n);state.attempts++;state.streak++;state.score+=10+Math.min((state.streak-1)*2,10);sound('ok');speak('找对啦');updateHUD();showReward(n,'找对啦！',()=>nextFind())}else{state.mistakes++;state.attempts++;state.streak=0;sound('bad');card.classList.remove('shake');void card.offsetWidth;card.classList.add('shake');showToast(`不是 ${n}，再看看哦`);updateHUD();setTimeout(()=>shuffleCardWithHidden(card),380)}}
function findTimeout(){state.mistakes++;state.attempts++;state.streak=0;updateHUD();showToast('小乌龟追上啦，再找一次！',1500);state.locked=true;setTimeout(()=>{shuffleVisibleRemaining();state.locked=false;nextFind()},900)}
function shuffleVisibleRemaining(){const cards=$$('.number-card').filter(c=>!c.classList.contains('passed')),parents=cards.map(c=>c.parentNode),shuffled=shuffle(cards);parents.forEach((p,i)=>p.appendChild(shuffled[i]))}
function startCount(){board.classList.add('hidden');countArena.classList.add('show');nextCount()}
function nextCount(){if(isFinished())return finishGame();state.target=state.sequence.find(n=>!state.completed.has(n));const d=DATA[state.target];$('#countObjects').innerHTML=makeObjects(state.target,d.e);const wrong=shuffle([1,2,3,4,5,6,7,8,9].filter(n=>n!==state.target)).slice(0,2),answers=shuffle([state.target,...wrong]);$('#answerRow').innerHTML=answers.map(n=>`<button class="answer-btn" data-answer="${n}">${n}</button>`).join('');$$('.answer-btn').forEach(b=>b.addEventListener('click',()=>chooseCountAnswer(b,Number(b.dataset.answer))));setPrompt('数一数：一共有几个？','可以用手指一个一个数');startRace(()=>countTimeout())}
function chooseCountAnswer(btn,n){if(state.locked)return;if(n===state.target){stopRace(true);btn.classList.add('correct');state.completed.add(state.target);state.attempts++;state.streak++;state.score+=10+Math.min((state.streak-1)*2,10);sound('ok');speak(`答对啦，一共有${CN[state.target]}个`);updateHUD();showReward(state.target,'数对啦！',()=>nextCount())}else{state.mistakes++;state.attempts++;state.streak=0;sound('bad');btn.classList.add('wrong');setTimeout(()=>btn.classList.remove('wrong'),420);showToast('再数一遍试试看');updateHUD()}}
function countTimeout(){state.mistakes++;state.attempts++;state.streak=0;updateHUD();showToast('时间到，再数一次！',1500);state.locked=true;setTimeout(()=>{state.locked=false;nextCount()},900)}
function startRace(onTimeout){if(!state.race)return;stopRace(false,true);state.timerStart=performance.now();state.raceTimeout=onTimeout;racePanel.classList.add('show');$('#turtle').style.left='8%';const rabbit=$('#sleepRabbit');rabbit.classList.remove('escape');rabbit.style.left='89%';$('#raceText').textContent='小白兔在终点睡觉，小乌龟出发啦！';tickRace()}
function tickRace(){if(!state.race||!state.raceTimeout)return;const elapsed=(performance.now()-state.timerStart)/1000,p=clamp(elapsed/state.time,0,1),left=Math.max(state.time-elapsed,0);$('#turtle').style.left=`${8+p*81}%`;$('#raceTime').textContent=`${left.toFixed(1)} 秒`;if(p>.72)$('#raceText').textContent='小乌龟快追上啦！';if(p>=1){const cb=state.raceTimeout;state.raceTimeout=null;state.timerId=null;$('#raceText').textContent='小乌龟追上睡觉的小白兔了！';$('#raceTime').textContent='时间到';sound('bad');speak('时间到，小乌龟追上小白兔了');setTimeout(()=>{racePanel.classList.remove('show');cb&&cb()},650);return}state.timerId=requestAnimationFrame(tickRace)}
function stopRace(success=false,immediate=false){if(state.timerId){cancelAnimationFrame(state.timerId);state.timerId=null}state.raceTimeout=null;if(!state.race||immediate){racePanel.classList.remove('show');return}if(success){const rabbit=$('#sleepRabbit');rabbit.classList.add('escape');$('#raceText').textContent='答对啦，小白兔醒来跑走了！';$('#raceTime').textContent='成功';setTimeout(()=>racePanel.classList.remove('show'),700)}else racePanel.classList.remove('show')}
function showReward(n,title,onDone){clearTimeout(state.rewardTimer);$('#rewardTitle').textContent=title;$('#rewardText').textContent=`数字 ${n} · ${CN[n]}`;reward.classList.add('show');miniConfetti();state.rewardTimer=setTimeout(()=>{reward.classList.remove('show');onDone&&onDone()},1250)}
function miniConfetti(){for(let i=0;i<24;i++){const p=document.createElement('i');p.className='confetti';p.style.left=Math.random()*100+'%';p.style.background=['#ff7272','#ffd66b','#54d8a4','#6c63ff','#ff7ca8'][i%5];p.style.animationDelay=Math.random()*.35+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),3000)}}
function isFinished(){return state.completed.size===state.selected.length}
function finishGame(){stopRace(false,true);state.locked=true;sound('finish');speak('太棒啦，你完成了所有数字挑战');miniConfetti();setTimeout(miniConfetti,250);const stars=state.mistakes===0?3:state.mistakes<=2?2:1;$('#resultStars').textContent='⭐'.repeat(stars)+'☆'.repeat(3-stars);$('#resultTitle').textContent=state.mistakes===0?'完美通关！':'挑战完成！';$('#resultText').textContent=state.mistakes===0?'全部一次答对，太厉害啦！':'每一次尝试都让数字记得更牢。';$('#resultScore').textContent=state.score;$('#resultCorrect').textContent=state.completed.size;$('#resultMistakes').textContent=state.mistakes;const key=`numberGameBest_${state.mode}`,best=Math.max(Number(localStorage.getItem(key)||0),state.score);localStorage.setItem(key,best);$('#bestScore').textContent=`最佳 ${best} 分`;setTimeout(()=>resultModal.classList.add('show'),350)}
function goSetup(){stopRace(false,true);clearTimeout(state.rewardTimer);if('speechSynthesis'in window)speechSynthesis.cancel();gameView.classList.add('hidden');setupView.classList.remove('hidden');$('#restartBtn').classList.add('hidden');resultModal.classList.remove('show');reward.classList.remove('show')}
function bind(){$$('.mode-card').forEach(b=>b.addEventListener('click',()=>chooseMode(b.dataset.mode)));$$('.count-chip').forEach(b=>b.addEventListener('click',()=>chooseCount(Number(b.dataset.count))));$('#raceToggle').addEventListener('change',e=>{$('#timeInput').disabled=!e.target.checked;$('#raceConfigText').textContent=e.target.checked?'开启：答题会有倒计时':'默认关闭：轻松学习'});$('#startBtn').addEventListener('click',startGame);$('#correctBtn').addEventListener('click',recognizeCorrect);$('#wrongBtn').addEventListener('click',()=>recognizeWrong(false));$('#settingsBtn').addEventListener('click',goSetup);$('#restartBtn').addEventListener('click',startGame);$('#playAgainBtn').addEventListener('click',startGame);$('#backSetupBtn').addEventListener('click',goSetup);$('#soundBtn').addEventListener('click',async()=>{audioWanted=!audioWanted;$('#soundBtn').classList.toggle('on',audioWanted);$('#soundBtn').textContent=audioWanted?'🔊 声音':'🔇 静音';if(audioWanted){await ensureAudio();tone(660,.15,'sine',.45);tone(880,.18,'sine',.4,.12);speak('声音已开启')}else if('speechSynthesis'in window)speechSynthesis.cancel()});reward.addEventListener('click',()=>{clearTimeout(state.rewardTimer)});window.addEventListener('keydown',e=>{if(state.mode==='recognize'&&!gameView.classList.contains('hidden')){if(e.key==='ArrowLeft')recognizeWrong(false);if(e.key==='ArrowRight')recognizeCorrect()}})}
bind();chooseMode('recognize');chooseCount(5);$('#timeInput').disabled=true;$('#soundBtn').classList.add('on');